version: '3.7'

services:
  db:
    image: postgres:11.2
    volumes:
      - ../volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=dicit
      - POSTGRES_PASSWORD=dicit
      - POSTGRES_DB=dicit-management
    networks:
      - my-network
    ports:
      - 5432:5432

  pgadm:
    image: dpage/pgadmin4
    links:
      - db:db
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "root"
      PGADMIN_DEFAULT_PASSWORD: "toor"
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge